# Afterglow Palette for Kitty
# Twilight dusk, violet skies, and radiant sunset clouds

background            #120e1c
foreground            #f3e8ff
cursor                #f3e8ff
cursor_text_color     #120e1c
selection_background  #362c52
selection_foreground  #f3e8ff

# URL underline color when hovering
url_color             #c084fc

# Kitty window border colors
active_border_color     #c084fc
inactive_border_color   #362c52
bell_border_color       #f43f5e

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #120e1c
active_tab_background   #c084fc
inactive_tab_foreground #c4b5fd
inactive_tab_background #191426
tab_bar_background      #120e1c

# The 16 terminal colors

# black
color0 #191426
color8 #362c52

# red
color1 #f43f5e
color9 #fb7185

# green
color2  #a78bfa
color10 #c4b5fd

# yellow
color3  #f472b6
color11 #fbcfe8

# blue
color4  #c084fc
color12 #d8b4fe

# magenta
color5  #e879f9
color13 #f0abfc

# cyan
color6  #818cf8
color14 #a5b4fc

# white
color7  #f3e8ff
color15 #ffffff
