[palettes.custom]
bg = "#120e1c"
mantle = "#191426"
crust = "#231d36"
surface0 = "#362c52"
surface1 = "#362c52"
surface2 = "#c084fc"
overlay0 = "#c4b5fd"
text = "#f3e8ff"
subtext = "#c4b5fd"
lavender = "#c084fc"
mauve = "#e879f9"
blue = "#c084fc"
red = "#f43f5e"
green = "#a78bfa"
yellow = "#f472b6"
