add_newline = true
palette = "custom"

format = """
$directory$git_branch$git_status$cmd_duration
$character"""

[directory]
home_symbol = "~"
read_only = " 󰌾"
style = "bold lavender"
truncation_length = 5
truncate_to_repo = false
truncation_symbol = "…/"
format = "[󰉋 $path]($style) "

[git_branch]
style = "subtext"
symbol = "󰘬 "
format = "on [$symbol$branch]($style) "
truncation_length = 16
truncation_symbol = "…"

[git_status]
style = "bold yellow"
format = "([\\[$all_status$ahead_behind\\]]($style) )"
conflicted = "󰞇 "
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[cmd_duration]
min_time = 2000
style = "bold yellow"
format = "took [$duration]($style) "

[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "dimmed subtext"

[username]
show_always = false
style_user = "bold lavender"
style_root = "bold red"
format = "[$user]($style) "

[package]
disabled = true

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "

[palettes.custom]
bg = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
overlay0 = "#6c7086"
text = "#cdd6f4"
subtext = "#a6adc8"
lavender = "#b4befe"
mauve = "#cba6f7"
blue = "#89b4fa"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
