#!/bin/bash

# The theme name is passed as the first argument ($1)
TARGET_THEME=$1
THEMES_DIR="$HOME/.config/themes"
ACTIVE_DIR="$HOME/.config/active-theme"

# Ensure target active directory exists
mkdir -p "$ACTIVE_DIR"

# Resolve target theme case-insensitively if exact folder not found
if [[ ! -d "$THEMES_DIR/$TARGET_THEME" ]]; then
    for d in "$THEMES_DIR"/*; do
        if [[ -d "$d" ]] && [[ "$(basename "$d" | tr '[:upper:]' '[:lower:]')" == "$(echo "$TARGET_THEME" | tr '[:upper:]' '[:lower:]')" ]]; then
            TARGET_THEME="$(basename "$d")"
            break
        fi
    done
fi

if [[ -d "$THEMES_DIR/$TARGET_THEME" ]]; then
    # Update symlinks
    [[ -f "$THEMES_DIR/$TARGET_THEME/hyprland-colors.conf" ]] && ln -sf "$THEMES_DIR/$TARGET_THEME/hyprland-colors.conf" "$ACTIVE_DIR/hyprland-colors.conf"
    [[ -f "$THEMES_DIR/$TARGET_THEME/hypr-colors.lua" ]] && ln -sf "$THEMES_DIR/$TARGET_THEME/hypr-colors.lua" "$ACTIVE_DIR/hypr-colors.lua"
    ln -sf "$THEMES_DIR/$TARGET_THEME/kitty-colors.conf" "$ACTIVE_DIR/kitty-colors.conf"
    ln -sf "$THEMES_DIR/$TARGET_THEME/quickshell-colors.json" "$ACTIVE_DIR/quickshell-colors.json"
    ln -sf "$THEMES_DIR/$TARGET_THEME/theme-name.txt" "$ACTIVE_DIR/theme-name.txt"
    ln -sf "$THEMES_DIR/$TARGET_THEME/starship-colors.toml" "$ACTIVE_DIR/starship-colors.toml"

    mkdir -p "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0"
    if [[ -f "$THEMES_DIR/$TARGET_THEME/gtk-colors.css" ]]; then
        cp "$THEMES_DIR/$TARGET_THEME/gtk-colors.css" "$HOME/.config/gtk-3.0/gtk.css"
        cp "$THEMES_DIR/$TARGET_THEME/gtk-colors.css" "$HOME/.config/gtk-4.0/gtk.css"
    fi

    # --- 3. Update GSettings (for libadwaita & portal sync) ---
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' 2>/dev/null
    gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark' 2>/dev/null

    # --- 4. Reload xsettingsd (if installed, for instant live GTK3 reloading) ---
    if command -v xsettingsd >/dev/null 2>&1; then
        killall -HUP xsettingsd 2>/dev/null
    fi

    # Update starship config
    if [[ -f "$HOME/.config/fish/base.toml" && -f "$THEMES_DIR/$TARGET_THEME/starship-colors.toml" ]]; then
        cat "$HOME/.config/fish/base.toml" "$THEMES_DIR/$TARGET_THEME/starship-colors.toml" > "$HOME/.config/starship.toml"
    fi

    # --- 5. Generate Hyprlock colors ---
    ACCENT_HEX="89b4fa"
    if [[ -f "$THEMES_DIR/$TARGET_THEME/quickshell-colors.json" ]] && command -v jq >/dev/null 2>&1; then
        ACCENT_RAW=$(jq -r '.accent // "#89b4fa"' "$THEMES_DIR/$TARGET_THEME/quickshell-colors.json" 2>/dev/null)
        ACCENT_HEX="${ACCENT_RAW#'#'}"
    fi
    cat <<EOF > "$ACTIVE_DIR/hyprlock-colors.conf"
# Auto-generated by apply-theme.sh for $TARGET_THEME
\$accent = rgb($ACCENT_HEX)
\$accentAlpha = $ACCENT_HEX
\$card_bg = rgba(14, 14, 18, 0.85)
\$text = rgb(248, 250, 252)
\$subtext = rgb(148, 163, 184)
EOF

    # Map active theme to the Neovim colorscheme name (case-insensitive)
    THEME_LOWER="$(echo "$TARGET_THEME" | tr '[:upper:]' '[:lower:]')"
    case "$THEME_LOWER" in
      "catppuccin")               NVIM_THEME="catppuccin-mocha" ;;
      "gruvbox")                  NVIM_THEME="gruvbox" ;;
      "tokyo-night"|"tokyonight")  NVIM_THEME="tokyonight-night" ;;
      "rose-pine"|"rosepine")    NVIM_THEME="rose-pine" ;;
      "nord")                     NVIM_THEME="nord" ;;
      "onedark")                  NVIM_THEME="onedark" ;;
      "dracula")                  NVIM_THEME="dracula" ;;
      "everforest")               NVIM_THEME="everforest" ;;
      "monokai-pro"|"monokaipro") NVIM_THEME="monokai-pro" ;;
      "ayu-mirage"|"ayumirage")   NVIM_THEME="ayu-mirage" ;;
      "e-ink"|"eink")            NVIM_THEME="e-ink" ;;
      "emerald")                  NVIM_THEME="emerald" ;;
      "gloaming")                 NVIM_THEME="gloaming" ;;
      *)                          NVIM_THEME="catppuccin" ;;
    esac

    # 1. Save current colorscheme to a dedicated state file
    mkdir -p "$HOME/.local/state/nvim"
    echo "$NVIM_THEME" > "$HOME/.local/state/nvim/active_colorscheme"

    # Read active transition (fallback to "simple" if file doesn't exist)
    TRANSITION="simple"
    if [[ -f "$ACTIVE_DIR/wallpaper-transition.txt" ]]; then
        TRANSITION=$(cat "$ACTIVE_DIR/wallpaper-transition.txt" | tr -d '\n\r ')
    fi
    [[ -z "$TRANSITION" ]] && TRANSITION="simple"

    # Handle "random" transition mode
    if [[ "$TRANSITION" == "random" ]]; then
        TRANSITIONS=("simple" "fade" "left" "right" "top" "bottom" "wipe" "wave" "outer")
        TRANSITION=${TRANSITIONS[$RANDOM % ${#TRANSITIONS[@]}]}
    fi

    # Find wallpaper directory
    WALLPAPER_DIR=""
    CANDIDATES=(
        "$HOME/Pictures/Wallpapers/$TARGET_THEME"
        "$HOME/Pictures/Wallpapers/$THEME_LOWER"
        "$HOME/git/MyLinuxSetup/Wallpapers/$TARGET_THEME"
        "$HOME/git/MyLinuxSetup/Wallpapers/$THEME_LOWER"
        "$HOME/Wallpapers/$TARGET_THEME"
        "$HOME/.config/Wallpapers/$TARGET_THEME"
    )
    for c in "${CANDIDATES[@]}"; do
        if [[ -d "$c" ]]; then
            WALLPAPER_DIR="$c"
            break
        fi
    done
    if [[ -z "$WALLPAPER_DIR" && -d "$HOME/Pictures/Wallpapers" ]]; then
        for d in "$HOME/Pictures/Wallpapers"/*; do
            if [[ -d "$d" ]] && [[ "$(basename "$d" | tr '[:upper:]' '[:lower:]')" == "$THEME_LOWER" ]]; then
                WALLPAPER_DIR="$d"
                break
            fi
        done
    fi

    # Apply wallpaper promptly
    RANDOM_WALLPAPER=""
    if [[ -n "$WALLPAPER_DIR" && -d "$WALLPAPER_DIR" ]]; then
        RANDOM_WALLPAPER=$(find "$WALLPAPER_DIR" -maxdepth 2 -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.webp" \) | shuf -n 1)
    fi
    # Global fallback if theme folder had no matching wallpapers
    if [[ -z "$RANDOM_WALLPAPER" ]]; then
        for fallback_dir in "$HOME/Pictures/Wallpapers" "$HOME/git/MyLinuxSetup/Wallpapers"; do
            if [[ -d "$fallback_dir" ]]; then
                RANDOM_WALLPAPER=$(find "$fallback_dir" -maxdepth 3 -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.webp" \) | shuf -n 1)
                [[ -n "$RANDOM_WALLPAPER" ]] && break
            fi
        done
    fi

    if [[ -n "$RANDOM_WALLPAPER" ]]; then
        if ! pgrep -x awww-daemon >/dev/null 2>&1; then
            awww-daemon &
            sleep 0.1
        fi
        awww img "$RANDOM_WALLPAPER" \
            --transition-type "$TRANSITION" \
            --transition-fps 144 \
            --transition-step 240 \
            --transition-bezier "0.25,0.1,0.25,1.0" &
    fi

    # Reload components
    if [[ -f "$ACTIVE_DIR/kitty-colors.conf" ]]; then
        kitty @ set-colors --all "$ACTIVE_DIR/kitty-colors.conf" 2>/dev/null &
    fi

    hyprctl reload 2>/dev/null &
    killall -SIGUSR1 kitty 2>/dev/null
    killall -SIGUSR1 nvim 2>/dev/null
    qs ipc call notch reloadTheme >/dev/null 2>&1 &

    notify-send "Theme Applied" "Activated $TARGET_THEME"
else
    notify-send "Error" "Theme $TARGET_THEME does not exist."
fi
