# Cloudscape Palette for Kitty
# Crisp daytime anime skies, summer cumulus clouds, and azure / aqua daybreak

background            #0c141c
foreground            #ecfeff
cursor                #ecfeff
cursor_text_color     #0c141c
selection_background  #28415c
selection_foreground  #ecfeff

# URL underline color when hovering
url_color             #22d3ee

# Kitty window border colors
active_border_color     #22d3ee
inactive_border_color   #28415c
bell_border_color       #f43f5e

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0c141c
active_tab_background   #22d3ee
inactive_tab_foreground #67e8f9
inactive_tab_background #121e2b
tab_bar_background      #0c141c

# The 16 terminal colors

# black
color0 #121e2b
color8 #28415c

# red
color1 #f43f5e
color9 #fb7185

# green
color2  #22d3ee
color10 #67e8f9

# yellow
color3  #06b6d4
color11 #a5f3fc

# blue
color4  #0891b2
color12 #22d3ee

# magenta
color5  #38bdf8
color13 #7dd3fc

# cyan
color6  #2dd4bf
color14 #5eead4

# white
color7  #ecfeff
color15 #ffffff
