[palettes.custom]
bg = "#0c141c"
mantle = "#121e2b"
crust = "#1b2c3e"
surface0 = "#28415c"
surface1 = "#28415c"
surface2 = "#22d3ee"
overlay0 = "#67e8f9"
text = "#ecfeff"
subtext = "#67e8f9"
lavender = "#22d3ee"
mauve = "#38bdf8"
blue = "#0891b2"
red = "#f43f5e"
green = "#22d3ee"
yellow = "#06b6d4"
