[SddmTheme]
Name=ii-pixel
Description=iNiR SDDM login screen — Material You dynamic colors
Type=sddm-theme
Author=iNiR project
Version=1.0
Website=https://github.com/snowarch/iNiR
Screenshot=
MainScript=Main.qml
ConfigFile=theme.conf

[General]
background=assets/background.png
defaultBackground=assets/background.png
blurRadius=50

# iNiR Material You colors — updated automatically by sync-pixel-sddm.py on wallpaper change
primaryColor=#BAC5EE
onPrimaryColor=#333F61
surfaceColor=#0D0E12
surfaceContainerColor=#121318
onSurfaceColor=#E4E5F0
onSurfaceVariantColor=#83848E
backgroundColor=#0D0E12
errorColor=#FA746F
materialShapeChars=true
