[palettes.custom]
bg = "#0e1411"
mantle = "#141d18"
crust = "#1d2922"
surface0 = "#2a3d33"
surface1 = "#2a3d33"
surface2 = "#34d399"
overlay0 = "#a7f3d0"
text = "#e6f4ea"
subtext = "#a7f3d0"
lavender = "#34d399"
mauve = "#d699b6"
blue = "#059669"
red = "#e67e80"
green = "#34d399"
yellow = "#10b981"
