# Crimson Palette for Kitty
# Pitch noir obsidian, glowing neon scarlet, and blood moon samurai

background            #0d0b0d
foreground            #fce7e7
cursor                #fce7e7
cursor_text_color     #0d0b0d
selection_background  #3d262d
selection_foreground  #fce7e7

# URL underline color when hovering
url_color             #ff453a

# Kitty window border colors
active_border_color     #ff453a
inactive_border_color   #3d262d
bell_border_color       #ff453a

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0d0b0d
active_tab_background   #ff453a
inactive_tab_foreground #fca5a5
inactive_tab_background #171214
tab_bar_background      #0d0b0d

# The 16 terminal colors

# black
color0 #171214
color8 #3d262d

# red
color1 #ff453a
color9 #ff6961

# green
color2  #ef4444
color10 #f87171

# yellow
color3  #f97316
color11 #fb923c

# blue
color4  #dc2626
color12 #ef4444

# magenta
color5  #f43f5e
color13 #fb7185

# cyan
color6  #fbbf24
color14 #fde047

# white
color7  #fce7e7
color15 #ffffff
