[palettes.custom]
bg = "#0d0b0d"
mantle = "#171214"
crust = "#241b1f"
surface0 = "#3d262d"
surface1 = "#3d262d"
surface2 = "#ff453a"
overlay0 = "#fca5a5"
text = "#fce7e7"
subtext = "#fca5a5"
lavender = "#ff453a"
mauve = "#f43f5e"
blue = "#dc2626"
red = "#ff453a"
green = "#ef4444"
yellow = "#f97316"
