# Abyss Palette for Kitty
# Deep ocean sapphire, underwater bioluminescence, and luminous azure abyss

background            #07101a
foreground            #e0f2fe
cursor                #e0f2fe
cursor_text_color     #07101a
selection_background  #1c3757
selection_foreground  #e0f2fe

# URL underline color when hovering
url_color             #38bdf8

# Kitty window border colors
active_border_color     #38bdf8
inactive_border_color   #1c3757
bell_border_color       #f43f5e

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #07101a
active_tab_background   #38bdf8
inactive_tab_foreground #7dd3fc
inactive_tab_background #0c1827
tab_bar_background      #07101a

# The 16 terminal colors

# black
color0 #0c1827
color8 #1c3757

# red
color1 #f43f5e
color9 #fb7185

# green
color2  #38bdf8
color10 #7dd3fc

# yellow
color3  #0284c7
color11 #bae6fd

# blue
color4  #0369a1
color12 #38bdf8

# magenta
color5  #2dd4bf
color13 #5eead4

# cyan
color6  #2563eb
color14 #60a5fa

# white
color7  #e0f2fe
color15 #ffffff
