[palettes.custom]
bg = "#07101a"
mantle = "#0c1827"
crust = "#12243a"
surface0 = "#1c3757"
surface1 = "#1c3757"
surface2 = "#38bdf8"
overlay0 = "#7dd3fc"
text = "#e0f2fe"
subtext = "#7dd3fc"
lavender = "#38bdf8"
mauve = "#2dd4bf"
blue = "#0369a1"
red = "#f43f5e"
green = "#38bdf8"
yellow = "#0284c7"
