[palettes.custom]
bg = "#0f1115"
mantle = "#171921"
crust = "#222631"
surface0 = "#333949"
surface1 = "#333949"
surface2 = "#cbd5e1"
overlay0 = "#94a3b8"
text = "#f8fafc"
subtext = "#94a3b8"
lavender = "#e2e8f0"
mauve = "#cbd5e1"
blue = "#94a3b8"
red = "#f43f5e"
green = "#cbd5e1"
yellow = "#e2e8f0"
