# Cyber Palette for Kitty
# Midnight neon shadow, electric magenta, cyberpunk alleys, and laser reflections

background            #0b0914
foreground            #fae8ff
cursor                #fae8ff
cursor_text_color     #0b0914
selection_background  #312353
selection_foreground  #fae8ff

# URL underline color when hovering
url_color             #d946ef

# Kitty window border colors
active_border_color     #d946ef
inactive_border_color   #312353
bell_border_color       #f43f5e

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0b0914
active_tab_background   #d946ef
inactive_tab_foreground #e879f9
inactive_tab_background #141021
tab_bar_background      #0b0914

# The 16 terminal colors

# black
color0 #141021
color8 #312353

# red
color1 #f43f5e
color9 #fb7185

# green
color2  #d946ef
color10 #e879f9

# yellow
color3  #c026d3
color11 #f0abfc

# blue
color4  #a855f7
color12 #c084fc

# magenta
color5  #06b6d4
color13 #22d3ee

# cyan
color6  #ec4899
color14 #f472b6

# white
color7  #fae8ff
color15 #ffffff
