[palettes.custom]
bg = "#0b0914"
mantle = "#141021"
crust = "#1e1732"
surface0 = "#312353"
surface1 = "#312353"
surface2 = "#d946ef"
overlay0 = "#e879f9"
text = "#fae8ff"
subtext = "#e879f9"
lavender = "#d946ef"
mauve = "#06b6d4"
blue = "#a855f7"
red = "#f43f5e"
green = "#d946ef"
yellow = "#c026d3"
