[palettes.custom]
bg = "#111614"
mantle = "#18201d"
crust = "#232d29"
surface0 = "#32403b"
surface1 = "#32403b"
surface2 = "#86efac"
overlay0 = "#bbf7d0"
text = "#f0fdf4"
subtext = "#bbf7d0"
lavender = "#86efac"
mauve = "#fed7aa"
blue = "#22c55e"
red = "#fb7185"
green = "#86efac"
yellow = "#4ade80"
