[palettes.custom]
bg = "#14110e"
mantle = "#1c1813"
crust = "#29231b"
surface0 = "#3d3326"
surface1 = "#3d3326"
surface2 = "#f59e0b"
overlay0 = "#fcd34d"
text = "#fef3c7"
subtext = "#fcd34d"
lavender = "#f59e0b"
mauve = "#c2410c"
blue = "#eab308"
red = "#ea580c"
green = "#f59e0b"
yellow = "#d97706"
