[palettes.custom]
bg = "#0a0d18"
mantle = "#101526"
crust = "#182038"
surface0 = "#263258"
surface1 = "#263258"
surface2 = "#818cf8"
overlay0 = "#a5b4fc"
text = "#e0e7ff"
subtext = "#a5b4fc"
lavender = "#818cf8"
mauve = "#c084fc"
blue = "#4f46e5"
red = "#f43f5e"
green = "#818cf8"
yellow = "#6366f1"
