# Gloaming Palette for Kitty

background            #182035
foreground            #d5daf0
cursor                #f2c4a4
cursor_text_color     #182035
selection_background  #263250
selection_foreground  #d5daf0

# URL underline color when hovering
url_color             #f2c4a4

# Kitty window border colors
active_border_color     #9fa8e0
inactive_border_color   #66739a
bell_border_color       #efb27b

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0d1220
active_tab_background   #b69cdc
inactive_tab_foreground #d5daf0
inactive_tab_background #131a2c
tab_bar_background      #0d1220

# The 16 terminal colors

# black
color0 #35415f
color8 #47547a

# red
color1 #e2788f
color9 #e2788f

# green
color2  #8dc7a3
color10 #8dc7a3

# yellow
color3  #efb27b
color11 #efb27b

# blue
color4  #78a2d9
color12 #78a2d9

# magenta
color5  #e09ab8
color13 #e09ab8

# cyan
color6  #82c9c4
color14 #82c9c4

# white
color7  #b6bdd9
color15 #a9b0cf
