[palettes.custom]
bg = "#182035"
mantle = "#131a2c"
crust = "#0d1220"
surface0 = "#263250"
surface1 = "#35415f"
surface2 = "#47547a"
overlay0 = "#66739a"
text = "#d5daf0"
subtext = "#a9b0cf"
lavender = "#9fa8e0"
mauve = "#b69cdc"
blue = "#78a2d9"
red = "#e2788f"
green = "#8dc7a3"
yellow = "#efb27b"
